### ISSUE TITLE
New mode : faster gauge decay instead of rank demotion - Treat vuln up as blunder instead of GCD drops

### ISSUE THREAD

**Issue by VilcsiTH** [Felscream/DragoonMayCry#28]
From a Black Mage point of view, I feel the drop system is too strict. Doing mechanics(looking away from Gaze, using Aetherial Manipulation to make it to a stack) usually gets me a blunder and ruins my rank. I tried increasing the GCD threshold to 1.000, but the same issues happen.

My suggestion is to speed up the rank decay when the player takes too long between abilities, but only apply a blunder on a vuln up. I'm not sure if blunder is already applied on vuln up, I got hit a few times and those triggered the blunder announcement, but that could've been a coincidence. In case it's already handled, adding an "Easy mode" toggle that replaces the GCD blunder(but not the vuln up blunder) with a decay speedup would be nice.

**Comment by Felscream** [comment]
Vulnerabilities and other debuffs you get when you fail a mechanic are considered blunders.
But since their IDs differ depending on the content you are running, some debuffs may not be tracked. They should all be there for Dawntrail (except the last dungeon).

You can adjust the delay before your GCD is considered 'dropped' in the job configuration for the plugin
- `/dmc conf` to open the configuration window
- job configuration
- select BLM
- adjust the time before your GCD is considered dropped.
If you have 'Estinien Must Die' enabled, you will just have to work on your uptime

Edit : Just reread your post, sorry, it's an uptime issue, you will have to work on it, you will get better

**Comment by Felscream** [comment]
You will have to work on your uptime on this one sorry

**Comment by Felscream** [comment]
After rerereading your suggestion I think it's actually a good idea

**Comment by Felscream** [comment]
Available on the plugin installer, version 1.2.4.0
