### ISSUE TITLE
Take latency into account when considering if GCD is dropped or not - Damage calculation seems off

### ISSUE THREAD

**Issue by YagamiVT** [Felscream/DragoonMayCry#7]
When testing the plugin, I noticed damage calculation is very off, an opener that deals nearly 500K in damage is somehow only worth a Dismal rank which shouldn't be the case, if we're going off DMC5, it should warrant at least an SS and then gradually drop or increase depending on how well people are performing

Adjusting your rotation to situation also punishes your rank too severely, adjusting for positionals also seems to punish the rank

Otherwise neat little plogon, however, where is Subhuman???

**Comment by Felscream** [comment]
The scaling is arbitrary. It's just made so that the ramping up from D to S or A to S is long enough to not trigger too much changes in a short time window, especially during openers. This would trigger too much changes for the dynamic BGM, and songs like Bury the Light would get too out of sync with your actual rank. I think it's also a way to promote uptime consistency, and not burst damage only.

Damage is read from flying text. It's not the best system, but it's good enough for general gamelay I think, maybe you are missing points from there.

The only things that will derank you hard are failed mechanics, clipping your GCD or holding your GCD for more than 0.1s. As long as you keep hitting buttons, you won't get deranked severely.
And I didn't have the energy to prepare Subhuman after the other 3.

**Comment by YagamiVT** [comment]
Understandable, but 0.1 seconds seems very punishing, given I saw my rank go from SS to B despite hitting CDs in time on GNB, unless that also was because of the damage values which, at level 100 shouldn't be such a drastic change

Maybe a small addition of an option to configure the punishment time because input latency and server lag can contribute to rank going down rapidly

I'm guessing the punishment mechanic was somewhat based on getting hit in DMC5? That is the only thing that comes to my head that would cause such drastic ranking decline

And well, when you can, it would be nice to see the addition of Subhuman, would fit perfectly with Papas Dante in the end

**Comment by Felscream** [comment]
Oh yeah if you are in S or above, delaying your GCD will bring you back to B, whereas if you are in A or lower, it will only take you down one rank. It is similar to getting hit in DmC. 

I didn't have server latency in mind when I made the system and yeah I should try to account for it but I don't know how to do it yet.

There is an explanation of how the plugin works if you click the "open" button left to "settings" on the plugin explorer page.

**Comment by Felscream** [comment]
Added a configurable GCD drop threshold on the job configuration window. Testing for the time being, maybe on stable next week.
